name: Build and Deploy (Docker)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_NAME: nex-koala-web
  TARBALL_NAME: nex-koala-web.tar
  CONTAINER_NAME: nex-koala-web
  TARGET_PORT: 8081

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: |
        docker build -t ${{ env.IMAGE_NAME }} .

    - name: Save Docker Image to Tar
      run: |
        docker save ${{ env.IMAGE_NAME }} -o ${{ env.TARBALL_NAME }}

    - name: Copy Image to Server
      uses: appleboy/scp-action@v0.1.6
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: ${{ env.TARBALL_NAME }}
        target: /tmp/
        overwrite: true

    - name: Load and Run Container on Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          docker rm -f ${{ env.CONTAINER_NAME }} || true
          docker load -i /tmp/${{ env.TARBALL_NAME }}
          docker run -d \
            --name ${{ env.CONTAINER_NAME }} \
            -p ${{ env.TARGET_PORT }}:80 \
            --restart always \
            ${{ env.IMAGE_NAME }}
