name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'
  NODE_VERSION: '20.x'
  APP_DIR: '/nex-koala/web'
  CLIENT_DIR: 'ClientApp'
  
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: ${{ env.CLIENT_DIR }}/package-lock.json

    - name: Restore .NET dependencies
      run: dotnet restore

    - name: Build .NET project
      run: dotnet build -c Release --no-restore
      
    - name: Install React dependencies
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi
      working-directory: ${{ env.CLIENT_DIR }}
      
    - name: Build React assets
      run: npm run build
      working-directory: ${{ env.CLIENT_DIR }}

    - name: Publish application
      run: dotnet publish -c Release -o ./publish

    - name: Verify Publish Output
      run: ls -la publish/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: nex-koala-package
        path: ./publish
        retention-days: 1

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: nex-koala-package

    - name: Test SSH Connection
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          echo "SSH connection successful!"
          ls -ld ${{ env.APP_DIR }}

    - name: Prepare Server Directory
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          # Create if missing, ignore if exists
          mkdir -p /nex-koala/web
          
          # Clean contents WITHOUT deleting directory
          find /nex-koala/web -mindepth 1 -delete
          
          # Verify ownership
          chown -R ${{ secrets.SSH_USER }}:${{ secrets.SSH_USER }} /nex-koala/web

    - name: Deploy Application Files
      uses: appleboy/scp-action@v0.1.6
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: 'publish/*'
        target: ${{ env.APP_DIR }}
        strip_components: 1
        overwrite: true
        rm: true

    - name: Restart Application Service
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          sudo systemctl restart invoice-web.service
          sudo systemctl status invoice-web.service
