name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'
  NODE_VERSION: '20.x'
  APP_DIR: '/nex-koala/web'
  WWWROOT_DIR: 'wwwroot'
  CLIENT_DIR: 'ClientApp'
  
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: ${{ env.CLIENT_DIR }}/package-lock.json

    - name: Build .NET
      run: |
        dotnet restore
        dotnet build -c Release
        dotnet publish -c Release -o ./publish

    - name: Cache Node Modules
      uses: actions/cache@v3
      with:
        path: ${{ env.CLIENT_DIR }}/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
          
    - name: Build React
      run: |
        npm ci
        npm run build
        mv dist/ ../publish/wwwroot/
      working-directory: ${{ env.CLIENT_DIR }}

    - name: Verify Publish Contents
      run: ls -la publish/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: nex-koala-package
        path: ./publish
        retention-days: 1
        
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: nex-koala-package
        path: publish 

    - name: Verify Downloaded Files
      run: |
        echo "Contents of publish directory:"
        ls -R publish/
        [ "$(ls -A publish)" ] || exit 1
        
    - name: Prepare Server Directory
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          # Create if missing, ignore if exists
          mkdir -p /nex-koala/web
          
          # Clean contents WITHOUT deleting directory
          find /nex-koala/web -mindepth 1 -delete
          
          # Verify ownership
          chown -R ${{ secrets.SSH_USER }}:${{ secrets.SSH_USER }} /nex-koala/web

    - name: Deploy Application Files
      uses: appleboy/scp-action@v0.1.6
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: "/nex-koala/web/*"
        target: ${{ env.APP_DIR }}
        recursive: true
        overwrite: true

    - name: Restart Application Service
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          sudo systemctl restart invoice-web.service
          sudo systemctl status invoice-web.service
