name: Build and Deploy (Frontend - Docker Hub)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_NAME: fld614/nex-koala-web
  CONTAINER_NAME: nex-koala-web
  TARGET_PORT: 8081

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: ⬇️ Checkout Source Code
      uses: actions/checkout@v4

    - name: 🔐 Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: 🛠 Build Docker Image
      run: |
        echo "Building Docker image: $IMAGE_NAME"
        docker build -t $IMAGE_NAME .

    - name: 📤 Push Image to Docker Hub
      run: |
        echo "Pushing Docker image to Docker Hub"
        docker push $IMAGE_NAME

    - name: 🚀 Deploy on Remote Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          echo "Stopping and removing existing container..."
          docker rm -f $CONTAINER_NAME || true

          echo "Pulling latest image..."
          docker pull $IMAGE_NAME

          echo "Starting new container..."
          docker run -d \
            --name $CONTAINER_NAME \
            -p $TARGET_PORT:80 \
            --restart always \
            $IMAGE_NAME

          echo "✅ Frontend deployed on $(hostname) at $(date)"
