name: Build and Deploy (Frontend - Docker)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_NAME: nex-koala-web
  CONTAINER_NAME: nex-koala-web
  TARGET_PORT: 8081
  DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USER }}/nex-koala-web:latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: ⬇️ Checkout Source Code
      uses: actions/checkout@v4

    - name: 🛠 Build Docker Image
      run: docker build -t ${{ env.IMAGE_NAME }} .

    - name: 🏷️ Tag Image for Docker Hub
      run: docker tag ${{ env.IMAGE_NAME }} ${{ env.DOCKER_IMAGE }}

    - name: 🔐 Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin

    - name: 🚀 Push to Docker Hub
      run: docker push ${{ env.DOCKER_IMAGE }}

    - name: 🚀 Deploy on Remote Host
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          docker rm -f ${{ env.CONTAINER_NAME }} || true
          docker pull ${{ env.DOCKER_IMAGE }}
          docker run -d \
            --name ${{ env.CONTAINER_NAME }} \
            -p ${{ env.TARGET_PORT }}:8080 \
            --restart always \
            ${{ env.DOCKER_IMAGE }}
