name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /nex-koala/web

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 16.x
        cache: 'npm'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build .NET
      run: dotnet build -c Release --no-restore

    - name: Build React
      run: |
        npm install
        npm run build
      working-directory: /nex-koala/web/ClientApp

    - name: Publish
      run: dotnet publish -c Release -o ./publish

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: nex-koala-package
        path: /nex-koala/web/publish

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: nex-koala-package

    - name: Deploy to server
      uses: appleboy/scp-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: ${{ secrets.SSH_PORT }}
        source: "/*"
        target: "/nex-koala/web/publish"
      
    - name: Restart service
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          sudo systemctl stop invoice-web.service
          sudo cp -r /nex-koala/web/publish/* /nex-koala/web/
          sudo rm -rf /nex-koala/web/publish
          sudo systemctl start invoice-web.service
          sudo systemctl status invoice-web.service
